routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::Routes();
Route::group(['middleware' => 'auth'],function (){
    Route::get('/', 'PromesaController@index')->middleware('verified');
    Route::resource('users', 'UserController');
    Route::resource('rols', 'RolController');
    Route::resource('clientes', 'ClienteController');
    Route::resource('promesas', 'PromesaController');
    Route::resource('saldos', 'SaldoController');
    Route::resource('ingresos', 'IngresoController');
    Route::get('/pdf/{id}', 'PromesaController@downloadPDF')->name('pdf');
    Route::get('/historial-pagos/{id}', 'ClienteController@pagos')->name('historial-pagos');
    Route::resource('historicos', 'HistoricoController');
    Route::resource('detalleCreditos', 'DetalleCreditoController');
    Route::get('/pdfCreditos/{id}', 'DetalleCreditoController@downloadPDF')->name('pdfCreditos');
    Route::resource('reportes', 'ReporteController');
    Route::post('reportesProm/export/', 'PromesaController@export')->name('reportesProm');
    Route::post('reportesProm/exportCliente/', 'PromesaController@exportCliente')->name('reportesPromCliente');
    Route::get('/pdfArchivos/{id}', 'PromesaController@retreivePagos')->name('pdfArchivos');
    Route::resource('comprobantes', 'CargaComprobantesController');
    Route::resource('rentaPendientes', 'RentaPendienteController');

});

app/Models/DetalleCredito.php
<?php

namespace App\Models;

use Eloquent as Model;



/**
 * Class DetalleCredito
 * @package App\Models
 * @version July 8, 2021, 5:49 pm UTC
 *
 * @property \App\Models\Cliente $idInstitucion
 * @property integer $id_institucion
 * @property string $no_contrato
 * @property number $monto_inicial
 * @property number $monto_pago
 * @property string $comprobante_pago
 * @property number $monto_actual
 * @property string $estatus
 * @property string|\Carbon\Carbon $created_at
 * @property string|\Carbon\Carbon $updated_at
 * @property string|\Carbon\Carbon $deleted_at
 */
class DetalleCredito extends Model
{


    public $table = 'detalle_credito';

    public $timestamps = false;




    public $fillable = [
        'id_institucion',
        'no_contrato',
        'monto_inicial',
        'monto_pago',
        'comprobante_pago',
        'monto_actual',
        'estatus',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_institucion' => 'integer',
        'no_contrato' => 'string',
        'monto_inicial' => 'decimal:2',
        'monto_pago' => 'decimal:2',
        'comprobante_pago' => 'string',
        'monto_actual' => 'decimal:2',
        'estatus' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_institucion' => 'nullable|integer',
        'no_contrato' => 'nullable|string|max:45',
        'monto_inicial' => 'nullable|numeric',
        'monto_pago' => 'nullable|numeric',
        'comprobante_pago' => 'nullable',
        'monto_actual' => 'nullable|numeric',
        'estatus' => 'nullable|string',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idInstitucion()
    {
        return $this->belongsTo(\App\Models\Cliente::class, 'id_institucion');
    }
}

app/Http/Controllers/DetalleCreditoController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use App\Models\Cliente;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\AppBaseController;
use App\Repositories\DetalleCreditoRepository;
use App\Http\Requests\CreateDetalleCreditoRequest;
use App\Http\Requests\UpdateDetalleCreditoRequest;

class DetalleCreditoController extends AppBaseController
{
    /** @var  DetalleCreditoRepository */
    private $detalleCreditoRepository;

    public function __construct(DetalleCreditoRepository $detalleCreditoRepo)
    {
        $this->detalleCreditoRepository = $detalleCreditoRepo;
    }

    /**
     * Display a listing of the DetalleCredito.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $detalleCreditos = $this->detalleCreditoRepository->all();

        return view('detalle_creditos.index')
            ->with('detalleCreditos', $detalleCreditos);
    }

    /**
     * Show the form for creating a new DetalleCredito.
     *
     * @return Response
     */
    public function create()
    {

        $clientes = Cliente::select('*')->where('Tipo', '=', 'CREDITO')->get();

        return view('detalle_creditos.create')->with('clientes', $clientes);
    }

    /**
     * Store a newly created DetalleCredito in storage.
     *
     * @param CreateDetalleCreditoRequest $request
     *
     * @return Response
     */
    public function store(CreateDetalleCreditoRequest $request)
    {
        $input = $request->all();
        //$file = $request->file('ruta');
        //dd($file);
        if ($file = $request->file('comprobante_pago')) {
            $image = base64_encode(file_get_contents($request->file('comprobante_pago')));
            $input['comprobante_pago'] = $image;
        } else {
            $input['comprobante_pago'] = null;
        }

        $detalleCredito = $this->detalleCreditoRepository->create($input);

        Flash::success('Detalle añadido satisfactoriamente.');

        return redirect(route('detalleCreditos.index'));
    }

    /**
     * Display the specified DetalleCredito.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $detalleCredito = $this->detalleCreditoRepository->find($id);

        if (empty($detalleCredito)) {
            Flash::error('Detalle Credito not found');

            return redirect(route('detalleCreditos.index'));
        }

        return view('detalle_creditos.show')->with('detalleCredito', $detalleCredito);
    }

    /**
     * Show the form for editing the specified DetalleCredito.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $detalleCredito = $this->detalleCreditoRepository->find($id);

        if (empty($detalleCredito)) {
            Flash::error('Detalle Credito not found');

            return redirect(route('detalleCreditos.index'));
        }

        $clientes = Cliente::select('*')->where('Tipo', '=', 'CREDITO')->get();

        return view('detalle_creditos.edit')->with('detalleCredito', $detalleCredito)->with('clientes', $clientes);
    }

    /**
     * Update the specified DetalleCredito in storage.
     *
     * @param int $id
     * @param UpdateDetalleCreditoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDetalleCreditoRequest $request)
    {
        //$detalleCredito = $this->detalleCreditoRepository->find($id);
        $input = $request->all();
        $query = DB::table('detalle_credito')->where('id', '=', $id);
        $detalleCredito = $query->first();
        $file = $request->file('comprobante_pago');

        if (empty($detalleCredito)) {
            Flash::error('Detalle Credito not found');

            return redirect(route('detalleCreditos.index'));
        }

        $update = $query
            ->update([
                'id_institucion' => $input['id_institucion'],
                'no_contrato' => $input['no_contrato'],
                'monto_inicial' => $input['monto_inicial'],
                'monto_pago' => $input['monto_pago'],
                'monto_actual' => $input['monto_actual'],
            ]);

        if ($file == null) {
            $up = $query
                ->update(['comprobante_pago' => null]);
        } else {
            $image = base64_encode(file_get_contents($request->file('comprobante_pago')));
            $up = $query
                ->update(['comprobante_pago' => $image]);
        }

        //$detalleCredito = $this->detalleCreditoRepository->update($request->all(), $id);

        Flash::success('Detalle actualizada.');

        return redirect(route('detalleCreditos.index'));
    }

    /**
     * Remove the specified DetalleCredito from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $detalleCredito = $this->detalleCreditoRepository->find($id);

        if (empty($detalleCredito)) {
            Flash::error('Detalle Credito not found');

            return redirect(route('detalleCreditos.index'));
        }

        $this->detalleCreditoRepository->delete($id);

        Flash::success('Detalle eliminado satisfactoriamente.');

        return redirect(route('detalleCreditos.index'));
    }

    public function downloadPDF($id)
    {
        //$id = \request()->request;
        //dd($id);
        $query = DB::table('detalle_credito')->where('id', '=', $id);
        $pdf = $query->first();
        //dd($pdf);
        $archivo = $pdf->comprobante_pago;
        $uuid = $pdf->id . $pdf->no_contrato;

        $decoded = base64_decode($archivo);
        $path = "xml_down/" . $uuid . ".pdf";
        file_put_contents($path, $decoded);
        header("Content-disposition: attachment; filename=$uuid.pdf");
        header("Content-type: application/pdf");
        readfile($path);
        unlink($path);

        //Flash::success('Factura descargada');

        //return redirect(route('facturas.index'));
    }
}

resources/views/detalle_creditos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detalle Credito
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'detalleCreditos.store', 'enctype' => 'multipart/form-data']) !!}

                    @include('detalle_creditos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/detalle_creditos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detalle Credito
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($detalleCredito, ['route' => ['detalleCreditos.update', $detalleCredito->id], 'method' => 'patch']) !!}

                        @include('detalle_creditos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/detalle_creditos/fields.blade.php
<!-- Id Institucion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_institucion', 'Institucion:') !!}
    <select name="id_institucion" id="id_institucion" class="form-control">
        <option value="">Seleccione una institución</option>
        @foreach ($clientes as $cliente)
            <option value="{{ $cliente->id }}">{{ $cliente->Cliente }}</option>
        @endforeach
    </select>
</div>

<!-- No Contrato Field -->
<div class="form-group col-sm-6">
    {!! Form::label('no_contrato', 'No Contrato:') !!}
    {!! Form::text('no_contrato', null, ['class' => 'form-control', 'maxlength' => 45, 'maxlength' => 45]) !!}
</div>

<!-- Monto Inicial Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_inicial', 'Monto Inicial:') !!}
    {!! Form::number('monto_inicial', null, ['class' => 'form-control']) !!}
</div>

<!-- Monto Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_pago', 'Monto Pago:') !!}
    {!! Form::number('monto_pago', null, ['class' => 'form-control']) !!}
</div>

<!-- Comprobante Pago Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('comprobante_pago', 'Comprobante Pago:') !!}
    <input type="file" name="comprobante_pago" class="form-control" accept="application/pdf" />
</div>

<!-- Monto Actual Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_actual', 'Monto Actual:') !!}
    {!! Form::number('monto_actual', null, ['class' => 'form-control']) !!}
</div>

<!-- Estatus Field -->
{{-- <div class="form-group col-sm-6">
    {!! Form::label('estatus', 'Estatus:') !!}
    {!! Form::text('estatus', null, ['class' => 'form-control']) !!}
</div> --}}

@push('scripts')
    <script type="text/javascript">
        $('#updated_at').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

@push('scripts')
    <script type="text/javascript">
        $('#deleted_at').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('detalleCreditos.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/detalle_creditos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Detalle Creditos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('detalleCreditos.create') }}">Añadir nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('detalle_creditos.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/detalle_creditos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detalle Credito
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('detalle_creditos.show_fields')
                    <a href="{{ route('detalleCreditos.index') }}" class="btn btn-default">volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/detalle_creditos/show_fields.blade.php
<!-- Id Institucion Field -->
<div class="form-group">
    {!! Form::label('id_institucion', 'Institución:') !!}
    <p>{{ $detalleCredito->id_institucion }}</p>
</div>

<!-- No Contrato Field -->
<div class="form-group">
    {!! Form::label('no_contrato', 'No Contrato:') !!}
    <p>{{ $detalleCredito->no_contrato }}</p>
</div>

<!-- Monto Inicial Field -->
<div class="form-group">
    {!! Form::label('monto_inicial', 'Monto Inicial:') !!}
    <p>{{ $detalleCredito->monto_inicial }}</p>
</div>

<!-- Monto Pago Field -->
<div class="form-group">
    {!! Form::label('monto_pago', 'Monto Pago:') !!}
    <p>{{ $detalleCredito->monto_pago }}</p>
</div>

<!-- Monto Actual Field -->
<div class="form-group">
    {!! Form::label('monto_actual', 'Monto Actual:') !!}
    <p>{{ $detalleCredito->monto_actual }}</p>
</div>

resources/views/detalle_creditos/table.blade.php
<div class="table-responsive">
    <table class="table" id="myTable">
        <thead>
            <tr>
                <th>Institución</th>
                <th>No Contrato</th>
                <th>Monto Inicial</th>
                <th>Monto Pago</th>
                <th>Comprobante Pago</th>
                <th>Monto Actual</th>
                <th>Estatus</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($detalleCreditos as $detalleCredito)
                <tr>
                    <td>{{ $detalleCredito->id_institucion }}</td>
                    <td>{{ $detalleCredito->no_contrato }}</td>
                    <td>{{ $detalleCredito->monto_inicial }}</td>
                    <td>{{ $detalleCredito->monto_pago }}</td>
                    <td>
                        @if ($detalleCredito->comprobante_pago == null)
                            No contiene archivo
                        @else
                            <a href="{!! route('pdfCreditos', [$detalleCredito->id]) !!}" class='btn-floating btn-sm btn-blue-grey'>Descargar</a>
                        @endif
                    </td>
                    <td>{{ $detalleCredito->monto_actual }}</td>
                    <td>{{ $detalleCredito->estatus }}</td>
                    <td>
                        {!! Form::open(['route' => ['detalleCreditos.destroy', $detalleCredito->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('detalleCreditos.show', [$detalleCredito->id]) }}"
                                class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                            <a href="{{ route('detalleCreditos.edit', [$detalleCredito->id]) }}"
                                class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                            {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>