routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::Routes();
Route::group(['middleware' => 'auth'],function (){
    Route::get('/', 'PromesaController@index')->middleware('verified');
    Route::resource('users', 'UserController');
    Route::resource('rols', 'RolController');
    Route::resource('clientes', 'ClienteController');
    Route::resource('promesas', 'PromesaController');
    Route::resource('saldos', 'SaldoController');
    Route::resource('ingresos', 'IngresoController');
    Route::get('/pdf/{id}', 'PromesaController@downloadPDF')->name('pdf');
    Route::get('/historial-pagos/{id}', 'ClienteController@pagos')->name('historial-pagos');
    Route::resource('historicos', 'HistoricoController');
    Route::resource('detalleCreditos', 'DetalleCreditoController');
    Route::get('/pdfCreditos/{id}', 'DetalleCreditoController@downloadPDF')->name('pdfCreditos');
    Route::resource('reportes', 'ReporteController');
    Route::post('reportesProm/export/', 'PromesaController@export')->name('reportesProm');
    Route::post('reportesProm/exportCliente/', 'PromesaController@exportCliente')->name('reportesPromCliente');
    Route::get('/pdfArchivos/{id}', 'PromesaController@retreivePagos')->name('pdfArchivos');
    Route::resource('comprobantes', 'CargaComprobantesController');
    Route::resource('rentaPendientes', 'RentaPendienteController');

});

app/Models/Promesa.php
<?php

namespace App\Models;

//use Eloquent as Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Promesa
 * @package App\Models
 * @version July 16, 2020, 6:47 am UTC
 *
 * @property \App\Models\Cliente $idCliente
 * @property number $promesa
 * @property number $pagado
 * @property integer $id_cliente
 * @property string $compromete_central
 * @property string $Compromete_cliente
 * @property string $Fecha_promesa
 * @property string $Fecha_pago
 * @property string $ruta
 * @property string|\Carbon\Carbon $created_at
 * @property string|\Carbon\Carbon $updated_at
 */
class Promesa extends Model
{

    public $table = 'Promesas';

    public $timestamps = false;

    public $fillable = [
        'promesa',
        //'pagado',
        'id_cliente',
        'compromete_central',
        'Compromete_cliente',
        'Fecha_promesa',
        'Fecha_pago',
        'ruta',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'idPromesas' => 'integer',
        'promesa' => 'decimal:0',
        //'pagado' => 'decimal:0',
        'id_cliente' => 'integer',
        'compromete_central' => 'string',
        'Compromete_cliente' => 'string',
        'Fecha_promesa' => 'date',
        'Fecha_pago' => 'date',
        'ruta' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function cliente()
    {
        return $this->belongsTo(Cliente::class, 'id_cliente');
    }

    public function comprobantes_pagos()
    {
        return $this->hasMany(ComprobantesPago::class, 'id_promesas');
    }
}

app/Http/Controllers/PromesaController.php
<?php

namespace App\Http\Controllers;

use DB;
use Flash;
use Response;
use Carbon\Carbon;
use App\Models\Cliente;
use App\Models\Promesa;
use Illuminate\Http\Request;
use App\Exports\PromesaExport;
use App\Exports\ClientesExport;
use App\Models\ComprobantesPago;

use Maatwebsite\Excel\Facades\Excel;
use App\Repositories\PromesaRepository;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CreatePromesaRequest;
use App\Http\Requests\UpdatePromesaRequest;
use Illuminate\Support\Facades\Auth;

class PromesaController extends AppBaseController
{
    /** @var  PromesaRepository */
    private $promesaRepository;

    public function __construct(PromesaRepository $promesaRepo)
    {
        $this->promesaRepository = $promesaRepo;
    }

    /**
     * Display a listing of the Promesa.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        //$promesas = $this->promesaRepository->all();
        $now = new \DateTime('Y');
        /*$promesas = DB::table('Promesas')
            ->join('Clientes', 'Promesas.id_cliente', '=', 'Clientes.id')
            ->select('Promesas.*', 'Clientes.cliente as cliente')
            ->where('Fecha_promesa', '=', '2020-10-02')
            ->paginate(50);*/
        /*$promesas = "select Promesas.idPromesas, Promesas.promesa, comprobantes_pagos.monto_pago as pagado, Promesas.id_cliente, Promesas.compromete_central, Promesas.Compromete_cliente,
        Promesas.Fecha_promesa, comprobantes_pagos.created_at as Fecha_pago, comprobantes_pagos.documento as ruta, Promesas.created_at, Promesas.updated_at,
         Clientes.cliente, Clientes.Tipo from Promesas inner join comprobantes_pagos on (comprobantes_pagos.id_promesas = Promesas.idPromesas)
         inner join Clientes on (Promesas.id_cliente = Clientes.id)
                where date_format(Promesas.fecha_promesa, '%Y') = date_format(sysdate(), '%Y');";*/
        /*$promesas = "select Promesas.*, Clientes.cliente, Clientes.Tipo from Promesas inner join Clientes on (Promesas.id_cliente = Clientes.id)
        where date_format(Promesas.fecha_promesa, '%Y') = date_format(sysdate(), '%Y');";*/
        if (Auth::user()->id_rol != 3) {
            $promesas = "select Promesas.idPromesas, Promesas.promesa, sum(comprobantes_pagos.monto_pago) as pagado, Promesas.id_cliente, Promesas.compromete_central, Promesas.Compromete_cliente,
        Promesas.Fecha_promesa, Promesas.created_at, Promesas.updated_at,
         Clientes.cliente, Clientes.Tipo from Promesas
         left join comprobantes_pagos on (comprobantes_pagos.id_promesas = Promesas.idPromesas)
         inner join Clientes on (Promesas.id_cliente = Clientes.id)
		where date_format(Promesas.fecha_promesa, '%Y') = date_format(sysdate(), '%Y')
		 group by Promesas.idPromesas
                order by Fecha_promesa desc;";
        } else {
            $promesas = "select Promesas.idPromesas, Promesas.promesa, sum(comprobantes_pagos.monto_pago) as pagado, Promesas.id_cliente, Promesas.compromete_central, Promesas.Compromete_cliente,
        Promesas.Fecha_promesa, Promesas.created_at, Promesas.updated_at,
         Clientes.cliente, Clientes.Tipo from Promesas
         left join comprobantes_pagos on (comprobantes_pagos.id_promesas = Promesas.idPromesas)
         inner join Clientes on (Promesas.id_cliente = Clientes.id)
		where date_format(Promesas.fecha_promesa, '%Y') = date_format(sysdate(), '%Y')
        and date_format(Promesas.fecha_promesa, '%Y-%m-%d') > '2021-11-01'
		 group by Promesas.idPromesas
                order by Fecha_promesa desc;";
        }

        $result1 = \Illuminate\Support\Facades\DB::SELECT($promesas);
        //$result11 = \Illuminate\Support\Facades\DB::SELECT($promesas1);
        //dd($result1);

        return view('promesas.index')
            ->with('promesas', $result1);
    }

    /**
     * Show the form for creating a new Promesa.
     *
     * @return Response
     */
    public function create()
    {
        $cliente = Cliente::all();
        return view('promesas.create')->with('clientes', $cliente);
    }

    /**
     * Store a newly created Promesa in storage.
     *
     * @param CreatePromesaRequest $request
     *
     * @return Response
     */
    public function store(CreatePromesaRequest $request)
    {
        $input = $request->all();
        //$file = $request->file('ruta');

        if ($file = $request->file('ruta')) {
            $image = base64_encode(file_get_contents($request->file('ruta')));
            $input['ruta'] = $image;
        } else {
            $input['ruta'] = null;
        }

        $promesa = $this->promesaRepository->create($input);
        /*if ($file = $request->file('ruta')) {
            $image = base64_encode(file_get_contents($request->file('ruta')));
            $input['ruta'] = $image;
        } else {
            $input['ruta'] = null;
        }*/
        //dd($promesa);

        $comprobante_pago = new ComprobantesPago;
        $comprobante_pago->id_promesas = $promesa->id;
        $comprobante_pago->documento = $input['ruta'];
        $comprobante_pago->fecha_pago = $input['Fecha_pago'];
        $comprobante_pago->monto_pago = $input['pagado'];
        $comprobante_pago->save();
        //dd($comprobante_pago);
        Flash::success('Promesa añadida.');

        return redirect(route('promesas.index'));
    }

    /**
     * Display the specified Promesa.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $promesa = $this->promesaRepository->find($id);

        if (empty($promesa)) {
            Flash::error('Promesa not found');

            return redirect(route('promesas.index'));
        }

        return view('promesas.show')->with('promesa', $promesa);
    }

    /**
     * Show the form for editing the specified Promesa.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $query = DB::table('Promesas')->where('idPromesas', '=', $id);
        $promesa = $query->first();
        $cliente = Cliente::all();
        //dd($promesa);

        if (empty($promesa)) {
            Flash::error('Promesa not found');

            return redirect(route('promesas.index'));
        }

        return view('promesas.edit')->with('promesa', $promesa)->with('clientes', $cliente);
    }

    /**
     * Update the specified Promesa in storage.
     *
     * @param int $id
     * @param UpdatePromesaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePromesaRequest $request)
    {
        $input = $request->all();
        $query = DB::table('Promesas')->where('idPromesas', '=', $id);
        $promesa = $query->first();
        $file = $request->file('ruta');
        //dd($file);
        //dd($input);

        if (empty($promesa)) {
            Flash::error('Promesa not found');

            return redirect(route('promesas.index'));
        }

        $update = $query
            ->update([
                'promesa' => $input['promesa'],
                //'pagado' => $input['pagado'],
                'id_cliente' => $input['id_cliente'],
                'compromete_central' => $input['compromete_central'],
                'Compromete_cliente' => $input['Compromete_cliente'],
                'Fecha_promesa' => $input['Fecha_promesa'],
                'Fecha_pago' => $input['Fecha_pago'],
            ]);

        if ($file == null) {
            $up = $query
                ->update(['ruta' => null]);
            $image = null;
        } else {
            $image = base64_encode(file_get_contents($request->file('ruta')));
            $up = $query
                ->update(['ruta' => $image]);
        }

        $comprobante_pago = new ComprobantesPago;
        $comprobante_pago->id_promesas = $id;
        $comprobante_pago->documento = $image;
        $comprobante_pago->fecha_pago = $input['Fecha_pago'];
        $comprobante_pago->monto_pago = $input['pagado'];
        $comprobante_pago->save();


        Flash::success('Promesa actualizada.');

        return redirect(route('promesas.index'));
    }

    /**
     * Remove the specified Promesa from storage.
     *
     * @param int $id
     *
     * @return Response
     * @throws \Exception
     *
     */
    public function destroy($id)
    {
        //$promesa = $this->promesaRepository->find($id);
        $query = DB::table('Promesas')->where('idPromesas', '=', $id);
        $promesa = $query->first();
        //dd($promesa);

        if (empty($promesa)) {
            Flash::error('Promesa not found');

            return redirect(route('promesas.index'));
        }

        $query->delete();

        Flash::success('Promesa eliminada.');

        return redirect(route('promesas.index'));
    }

    public function downloadPDF($id)
    {
        //$id = \request()->request;
        $query = ComprobantesPago::find($id);
        //$query = DB::table('Promesas')->where('idPromesas', '=', $id);
        //$pdf = $query->first();
        //dd($pdf);
        $archivo = $query->documento;
        $uuid = $query->id_promesas . "-" . $id;

        $decoded = base64_decode($archivo);
        $path = "xml_down/" . $uuid . ".pdf";
        file_put_contents($path, $decoded);
        header("Content-disposition: attachment; filename=$uuid.pdf");
        header("Content-type: application/pdf");
        readfile($path);
        unlink($path);

        //Flash::success('Factura descargada');

        //return redirect(route('facturas.index'));
    }

    public function export()
    {
        $input = request()->all();
        $carbon = new \Carbon\Carbon();
        $date = $carbon->now();
        $date = $date->format('d-m-Y');

        $file_name = "Reporte-" . $date . ".xlsx";
        return (new PromesaExport($input['inicio'], $input['fin']))->download($file_name);

resources/views/promesas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Promesa
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'promesas.store', 'enctype' => 'multipart/form-data']) !!}

                        @include('promesas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/promesas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Promesa
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($promesa, ['route' => ['promesas.update', $promesa->idPromesas], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                        @include('promesas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/promesas/fields.blade.php
<!-- Promesa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('promesa', 'Promesa:') !!}
    {!! Form::number('promesa', null, ['class' => 'form-control', 'required']) !!}
</div>

<!-- Pagado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pagado', 'Nuevo pago:') !!}
    {!! Form::number('pagado', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    <label for="exampleFormControlSelect1">Cliente:</label>
    <select class="form-control col-sm-6" name="id_cliente" id="exampleFormControlSelect1">
        @foreach($clientes as $cliente)
            <option value="{!! $cliente->id !!}">{!! $cliente->Cliente !!}</option>
        @endforeach
    </select>
</div>

<!-- Compromete Central Field -->
<div class="form-group col-sm-6">
    {!! Form::label('compromete_central', 'Compromete Central:') !!}
    {!! Form::text('compromete_central', null, ['class' => 'form-control' , 'required']) !!}
</div>

<!-- Compromete Cliente Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Compromete_cliente', 'Compromete Cliente:') !!}
    {!! Form::text('Compromete_cliente', null, ['class' => 'form-control' , 'required']) !!}
</div>

<!-- Fecha Promesa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Fecha_promesa', 'Fecha Promesa:') !!}
    {!! Form::text('Fecha_promesa', null, ['class' => 'form-control','id'=>'Fecha_promesa' , 'required']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#Fecha_promesa').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Fecha Pago Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Fecha_pago', 'Fecha Pago:') !!}
    {!! Form::text('Fecha_pago', null, ['class' => 'form-control','id'=>'Fecha_pago' , 'required']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#Fecha_pago').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Ruta Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ruta', 'Archivo:') !!}
    {!! Form::file('ruta', null, ['class' => 'form-control' , 'required']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('promesas.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/promesas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Promesas</h1>
        <h1 class="pull-right">
            @if (Auth::user()->id_rol == '1' || Auth::user()->id_rol == '4')
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
                href="{{ route('promesas.create') }}">Añadir</a>
                @endif
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('layouts.errors')
        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('promesas.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/promesas/pagoedit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pago
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($comprobante_pagos, ['route' => ['comprobantes.update', $comprobante_pagos->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                    <div class="modal-body">
                        {{ Form::hidden('id_promesas', $comprobante_pagos->id_promesas)}}
                        <!-- Fecha Promesa Field -->
                        <div class="form-group col-sm-12">
                            {!! Form::label('Fecha_promesa', 'Fecha Promesa:') !!}
                            {!! Form::text('Fecha_promesa', $comprobante_pagos->fecha_pago, ['class' => 'form-control', 'id' => 'Fecha_promesa', 'required']) !!}
                        </div>
                        <div class="form-group col-sm-12">
                        <p>
                            Archivo:
                            @if ($comprobante_pagos->documento == null)
                                No contiene archivo
                            @else
                                <a href="{!! route('pdf', [$comprobante_pagos->id]) !!}" class='btn-floating btn-sm btn-blue-grey'>Descargar</a>
                            @endif
                        </p>
                        </div>

                        <!-- Ruta Field -->
                        <div class="form-group col-sm-12">
                            {!! Form::label('ruta', 'Archivo:') !!}
                            {!! Form::file('ruta', null, ['class' => 'form-control', 'required']) !!}
                        </div>

                        <div class="form-group col-sm-12">
                            <label for="comentario">Comentario (opcional)</label>
                            {{ Form::textarea('comentario', $comprobante_pagos->comentario, [
                                'class' => 'form-control',
                                'rows' => 1,
                                'name' => 'comentario',
                                'id' => 'comentario',
                            ]) }}
                        </div>

                        <!-- Submit Field -->
                        <div class="form-group col-sm-12">
                            {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
                            <a class="btn btn-danger" href="{{ url()->previous() }}">Cancelar</a>
                        </div>


                    </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/promesas/pagos.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Detalle de pagos</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
                href="javascript:window.open('','_self').close();">Cerrar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('layouts.errors')
        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary py-2">
            <!-- Trigger the modal with a button -->
            @if (Auth::user()->id_rol != '3')
                @if (Auth::user()->id_rol != '5')
                    <button type="button" class="btn btn-info " data-toggle="modal" data-target="#myModal">Cargar
                        Nuevo</button>
                @endif
            @endif
            <div class="box-body">
                @include('promesas.pagostable')
            </div>
        </div>
        <div class="text-center">
            <!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Seleccione su nuevo documento a cargar</h4>
                        </div>
                        <div class="modal-body">
                            {!! Form::open(['route' => 'comprobantes.store', 'enctype' => 'multipart/form-data']) !!}
                            {!! Form::hidden('id_promesas', $idPromesa) !!}

                            <!-- Fecha Promesa Field -->
                            <div class="form-group col-sm-12">
                                {!! Form::label('Fecha_promesa', 'Fecha Promesa:') !!}
                                {!! Form::text('Fecha_promesa', null, ['class' => 'form-control', 'id' => 'Fecha_promesa', 'required']) !!}
                            </div>

                            <!-- Ruta Field -->
                            <div class="form-group col-sm-12">
                                {!! Form::label('ruta', 'Archivo:') !!}
                                {!! Form::file('ruta', null, ['class' => 'form-control', 'required']) !!}
                            </div>

                            <div class="form-group col-sm-12">
                                <label for = "comentario">Comentario (opcional)</label>
                                <textarea class = "form-control" name="comentario" rows = "3" placeholder = "Comentario (opcional)"></textarea>
                            </div>

                            <!-- Submit Field -->
                            <div class="form-group col-sm-12">
                                {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
                            </div>

                            {!! Form::close() !!}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script type="text/javascript">
            $('#Fecha_promesa').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: true,
                sideBySide: true
            })
        </script>
    @endpush
@endsection

resources/views/promesas/pagostable.blade.php
<div class="table-responsive">
    <table class="table table-hover text-center" id="myTable">
        <thead>
            <tr>
                <th>ID</th>
                {{-- <th>Monto pago</th> --}}
                <th>Fecha pago</th>
                {{-- <th>Promesa</th>
                <th>Cliente</th> --}}
                <th>Documento</th>
                <th>Comentario</th>
                @if (Auth::user()->id_rol != '3')
                    @if (Auth::user()->id_rol != '5')
                        <th>Editar</th>
                        <th>Eliminar</th>
                    @endif
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach ($promesas as $promesa)
                <tr>
                    <td> {{ $promesa->idComprobante }}</td>
                    {{-- <td>$ {{ number_format($promesa->monto_pago, 2, '.', '') }}</td> --}}
                    <td>{{ $promesa->fecha_pago }}</td>
                    {{-- <td>{{ number_format($promesa->promesa, 2, '.', '') }}</td>
                    <td>{{ $promesa->cliente }}</td> --}}
                    <td>
                        @if ($promesa->documento == null)
                            No contiene archivo
                        @else
                            <a href="{!! route('pdf', [$promesa->idComprobante]) !!}" class='btn-floating btn-sm btn-blue-grey'>Descargar</a>
                        @endif
                    </td>
                    <td>
                        {{ $promesa->comentario }}
                    </td>
                    {{-- <td>
                    @if ($promesa->ruta == null)
                        No contiene archivo
                    @else
                        <a href="{!! route('pdf', [$promesa->idPromesas]) !!}"
                           class='btn-floating btn-sm btn-blue-grey'>Descargar</a>
                    @endif
                </td> --}}
                    @if (Auth::user()->id_rol != '3')
                        @if (Auth::user()->id_rol != '5')
                            {!! Form::open(['route' => ['comprobantes.destroy', $promesa->idComprobante], 'method' => 'delete']) !!}
                            <td><a href="{{ route('comprobantes.edit', [$promesa->idComprobante]) }}"
                                class='btn btn-default btn-xs btn-block'>Editar</a></td>
                            <td>{!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm ', 'onclick' => "return confirm('Are you sure?')"]) !!}</td>

                            {!! Form::close() !!}
                        @endif
                    @endif
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/promesas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Promesa
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('promesas.show_fields')
                    <a href="{{ route('promesas.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/promesas/show_fields.blade.php
<!-- Promesa Field -->
<div class="form-group">
    {!! Form::label('promesa', 'Promesa:') !!}
    <p>{{ $promesa->promesa }}</p>
</div>

<!-- Pagado Field -->
<div class="form-group">
    {!! Form::label('pagado', 'Pagado:') !!}
    <p>{{ $promesa->pagado }}</p>
</div>

<!-- Id Cliente Field -->
<div class="form-group">
    {!! Form::label('id_cliente', 'Id Cliente:') !!}
    <p>{{ $promesa->id_cliente }}</p>
</div>

<!-- Compromete Central Field -->
<div class="form-group">
    {!! Form::label('compromete_central', 'Compromete Central:') !!}
    <p>{{ $promesa->compromete_central }}</p>
</div>

<!-- Compromete Cliente Field -->
<div class="form-group">
    {!! Form::label('Compromete_cliente', 'Compromete Cliente:') !!}
    <p>{{ $promesa->Compromete_cliente }}</p>
</div>

<!-- Fecha Promesa Field -->
<div class="form-group">
    {!! Form::label('Fecha_promesa', 'Fecha Promesa:') !!}
    <p>{{ $promesa->Fecha_promesa }}</p>
</div>

<!-- Fecha Pago Field -->
<div class="form-group">
    {!! Form::label('Fecha_pago', 'Fecha Pago:') !!}
    <p>{{ $promesa->Fecha_pago }}</p>
</div>

<!-- Ruta Field -->
<div class="form-group">
    {!! Form::label('ruta', 'Ruta:') !!}
    <p>{{ $promesa->ruta }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $promesa->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $promesa->updated_at }}</p>
</div>