routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::Routes();
Route::group(['middleware' => 'auth'],function (){
    Route::get('/', 'PromesaController@index')->middleware('verified');
    Route::resource('users', 'UserController');
    Route::resource('rols', 'RolController');
    Route::resource('clientes', 'ClienteController');
    Route::resource('promesas', 'PromesaController');
    Route::resource('saldos', 'SaldoController');
    Route::resource('ingresos', 'IngresoController');
    Route::get('/pdf/{id}', 'PromesaController@downloadPDF')->name('pdf');
    Route::get('/historial-pagos/{id}', 'ClienteController@pagos')->name('historial-pagos');
    Route::resource('historicos', 'HistoricoController');
    Route::resource('detalleCreditos', 'DetalleCreditoController');
    Route::get('/pdfCreditos/{id}', 'DetalleCreditoController@downloadPDF')->name('pdfCreditos');
    Route::resource('reportes', 'ReporteController');
    Route::post('reportesProm/export/', 'PromesaController@export')->name('reportesProm');
    Route::post('reportesProm/exportCliente/', 'PromesaController@exportCliente')->name('reportesPromCliente');
    Route::get('/pdfArchivos/{id}', 'PromesaController@retreivePagos')->name('pdfArchivos');
    Route::resource('comprobantes', 'CargaComprobantesController');
    Route::resource('rentaPendientes', 'RentaPendienteController');

});

app/Models/RentaPendiente.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class RentaPendiente
 * @package App\Models
 * @version December 21, 2021, 6:07 am UTC
 *
 * @property string $grupo
 * @property number $proyecto
 * @property integer $id_cliente
 * @property string $estacionamiento
 * @property string $concepto
 * @property string $rfc
 * @property number $monto_cxp
 * @property string $fecha_entrega
 * @property string $estatus
 * @property string $observaciones
 * @property string $gerente
 * @property string|\Carbon\Carbon $created_at
 * @property string|\Carbon\Carbon $updated_at
 */
class RentaPendiente extends Model
{
    public $table = 'rentas_pendientes';

    public $timestamps = false;

	protected $primaryKey = 'id_rentas';

	protected $dates = [
		'fecha_entrega'
	];

    public $fillable = [
        'grupo',
        'proyecto',
        'id_cliente',
        'estacionamiento',
        'concepto',
        'rfc',
        'monto_cxp',
        'fecha_entrega',
        'estatus',
        'observaciones',
        'gerente',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id_rentas' => 'integer',
        'grupo' => 'string',
        'proyecto' => 'decimal:1',
        'id_cliente' => 'integer',
        'estacionamiento' => 'string',
        'concepto' => 'string',
        'rfc' => 'string',
        'monto_cxp' => 'decimal:2',
        'fecha_entrega' => 'date',
        'estatus' => 'string',
        'observaciones' => 'string',
        'gerente' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'grupo' => 'nullable|string|max:55',
        'proyecto' => 'nullable|numeric',
        'id_cliente' => 'nullable|integer',
        'estacionamiento' => 'nullable|string|max:255',
        'concepto' => 'nullable|string|max:255',
        'rfc' => 'nullable|string|max:14',
        'monto_cxp' => 'nullable|numeric',
        'fecha_entrega' => 'nullable',
        'estatus' => 'nullable|string',
        'observaciones' => 'nullable|string|max:1000',
        'gerente' => 'nullable|string|max:255',
    ];


}

app/Http/Controllers/RentaPendienteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRentaPendienteRequest;
use App\Http\Requests\UpdateRentaPendienteRequest;
use App\Repositories\RentaPendienteRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\Gerente;
use Illuminate\Http\Request;
use Flash;
use Response;

class RentaPendienteController extends AppBaseController
{
    /** @var  RentaPendienteRepository */
    private $rentaPendienteRepository;

    public function __construct(RentaPendienteRepository $rentaPendienteRepo)
    {
        $this->rentaPendienteRepository = $rentaPendienteRepo;
    }

    /**
     * Display a listing of the RentaPendiente.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $rentaPendientes = $this->rentaPendienteRepository->all();

        return view('renta_pendientes.index')
            ->with('rentaPendientes', $rentaPendientes);
    }

    /**
     * Show the form for creating a new RentaPendiente.
     *
     * @return Response
     */
    public function create()
    {
        $edit_id = false;
        $gerentes = Gerente::select('name')->distinct()->get();

        return view('renta_pendientes.create', compact('edit_id', 'gerentes'));
    }

    /**
     * Store a newly created RentaPendiente in storage.
     *
     * @param CreateRentaPendienteRequest $request
     *
     * @return Response
     */
    public function store(CreateRentaPendienteRequest $request)
    {
        $input = $request->all();

        $rentaPendiente = $this->rentaPendienteRepository->create($input);

        Flash::success('Renta añadida satisfactoriamente.');

        return redirect(route('rentaPendientes.index'));
    }

    /**
     * Display the specified RentaPendiente.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $rentaPendiente = $this->rentaPendienteRepository->find($id);

        if (empty($rentaPendiente)) {
            Flash::error('Renta Pendiente not found');

            return redirect(route('rentaPendientes.index'));
        }

        return view('renta_pendientes.show')->with('rentaPendiente', $rentaPendiente);
    }

    /**
     * Show the form for editing the specified RentaPendiente.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $rentaPendiente = $this->rentaPendienteRepository->find($id);

        if (empty($rentaPendiente)) {
            Flash::error('Renta Pendiente not found');

            return redirect(route('rentaPendientes.index'));
        }

        $gerentes = Gerente::select('name')->distinct()->get();
        return view('renta_pendientes.edit', compact('gerentes'))->with('rentaPendiente', $rentaPendiente)->with('edit_id', $rentaPendiente->id_rentas);
    }

    /**
     * Update the specified RentaPendiente in storage.
     *
     * @param int $id
     * @param UpdateRentaPendienteRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRentaPendienteRequest $request)
    {
        $rentaPendiente = $this->rentaPendienteRepository->find($id);

        if (empty($rentaPendiente)) {
            Flash::error('Renta Pendiente not found');

            return redirect(route('rentaPendientes.index'));
        }

        $rentaPendiente = $this->rentaPendienteRepository->update($request->all(), $id);

        Flash::success('Renta actualizada.');

        return redirect(route('rentaPendientes.index'));
    }

    /**
     * Remove the specified RentaPendiente from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $rentaPendiente = $this->rentaPendienteRepository->find($id);

        if (empty($rentaPendiente)) {
            Flash::error('Renta Pendiente not found');

            return redirect(route('rentaPendientes.index'));
        }

        $this->rentaPendienteRepository->delete($id);

        Flash::success('Renta eliminada.');

        return redirect(route('rentaPendientes.index'));
    }
}

resources/views/renta_pendientes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Renta Pendiente
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'rentaPendientes.store']) !!}

                        @include('renta_pendientes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/renta_pendientes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Renta Pendiente
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($rentaPendiente, ['route' => ['rentaPendientes.update', $rentaPendiente->id_rentas], 'method' => 'patch']) !!}

                        @include('renta_pendientes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/renta_pendientes/fields.blade.php
@livewire('rentas-pendientes', ['edit_id' => $edit_id])

<!-- Grupo Field -->
{{-- <div class="form-group col-sm-6">
    {!! Form::label('grupo', 'Grupo:') !!}
    {!! Form::text('grupo', null, ['class' => 'form-control', 'maxlength' => 55, 'maxlength' => 55, 'required']) !!}
</div> --}}

<!-- Concepto Field -->
<div class="form-group col-sm-6">
    {!! Form::label('concepto', 'Concepto:') !!}
    {!! Form::text('concepto', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255, 'required']) !!}
</div>

<!-- Monto Cxp Field -->
<div class="form-group col-sm-6">
    {!! Form::label('monto_cxp', 'Monto Cxp:') !!}
    {!! Form::number('monto_cxp', null, ['class' => 'form-control', 'required' , 'step' => "0.01"]) !!}
</div>

<!-- Fecha Entrega Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_entrega', 'Fecha Entrega:') !!}
    {!! Form::text('fecha_entrega', null, ['class' => 'form-control', 'id' => 'fecha_entrega', 'required']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fecha_entrega').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Estatus Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estatus', 'Estatus:') !!}
    <select name="estatus" class="form-control" required>
        <option value="En tiempo">En tiempo</option>
        <option value="Vencido">Vencido</option>
    </select>
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control', 'maxlength' => 1000, 'maxlength' => 1000, 'required']) !!}
</div>

<!-- Gerente Field -->
<div class="form-group col-sm-6">
    {!! Form::label('gerente', 'Gerente:') !!}
    <select name="gerente" class="form-control" required>
        @foreach ($gerentes as $gerente)
            <option value="{{$gerente->name}}">{{$gerente->name}}</option>
        @endforeach
    </select>
</div>

{{-- <!-- Created At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_at', 'Created At:') !!}
    {!! Form::text('created_at', null, ['class' => 'form-control','id'=>'created_at']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#created_at').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Updated At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_at', 'Updated At:') !!}
    {!! Form::text('updated_at', null, ['class' => 'form-control','id'=>'updated_at']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#updated_at').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush --}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('rentaPendientes.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/renta_pendientes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Renta Pendientes</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('rentaPendientes.create') }}">Añadir</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('renta_pendientes.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/renta_pendientes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Renta Pendiente
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('renta_pendientes.show_fields')
                    <a href="{{ route('rentaPendientes.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/renta_pendientes/show_fields.blade.php
<!-- Grupo Field -->
<div class="form-group">
    {!! Form::label('grupo', 'Grupo:') !!}
    <p>{{ $rentaPendiente->grupo }}</p>
</div>

<!-- Proyecto Field -->
<div class="form-group">
    {!! Form::label('proyecto', 'Proyecto:') !!}
    <p>{{ $rentaPendiente->proyecto }}</p>
</div>

<!-- Id Cliente Field -->
<div class="form-group">
    {!! Form::label('id_cliente', 'Id Cliente:') !!}
    <p>{{ $rentaPendiente->id_cliente }}</p>
</div>

<!-- Estacionamiento Field -->
<div class="form-group">
    {!! Form::label('estacionamiento', 'Estacionamiento:') !!}
    <p>{{ $rentaPendiente->estacionamiento }}</p>
</div>

<!-- Concepto Field -->
<div class="form-group">
    {!! Form::label('concepto', 'Concepto:') !!}
    <p>{{ $rentaPendiente->concepto }}</p>
</div>

<!-- Rfc Field -->
<div class="form-group">
    {!! Form::label('rfc', 'Rfc:') !!}
    <p>{{ $rentaPendiente->rfc }}</p>
</div>

<!-- Monto Cxp Field -->
<div class="form-group">
    {!! Form::label('monto_cxp', 'Monto Cxp:') !!}
    <p>{{ $rentaPendiente->monto_cxp }}</p>
</div>

<!-- Fecha Entrega Field -->
<div class="form-group">
    {!! Form::label('fecha_entrega', 'Fecha Entrega:') !!}
    <p>{{ $rentaPendiente->fecha_entrega }}</p>
</div>

<!-- Estatus Field -->
<div class="form-group">
    {!! Form::label('estatus', 'Estatus:') !!}
    <p>{{ $rentaPendiente->estatus }}</p>
</div>

<!-- Observaciones Field -->
<div class="form-group">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    <p>{{ $rentaPendiente->observaciones }}</p>
</div>

<!-- Gerente Field -->
<div class="form-group">
    {!! Form::label('gerente', 'Gerente:') !!}
    <p>{{ $rentaPendiente->gerente }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $rentaPendiente->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $rentaPendiente->updated_at }}</p>
</div>

resources/views/renta_pendientes/table.blade.php
<div class="table-responsive">
    <table class="table" id="myTable">
        <thead>
            <tr>
                {{-- <th>Grupo</th> --}}
                <th>Proyecto</th>
                <th>Cliente</th>
                <th>Estacionamiento</th>
                <th>Concepto</th>
                <th>Rfc</th>
                <th>Monto Cxp</th>
                <th>Fecha Entrega</th>
                <th>Estatus</th>
                <th>Observaciones</th>
                <th>Gerente</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rentaPendientes as $rentaPendiente)
                <tr>
                    {{-- <td>{{ $rentaPendiente->grupo }}</td> --}}
                    <td>{{ $rentaPendiente->proyecto }}</td>
                    <td>{{ $rentaPendiente->id_cliente }}</td>
                    <td>{{ $rentaPendiente->estacionamiento }}</td>
                    <td>{{ $rentaPendiente->concepto }}</td>
                    <td>{{ $rentaPendiente->rfc }}</td>
                    <td>{{ $rentaPendiente->monto_cxp }}</td>
                    <td>{{ $rentaPendiente->fecha_entrega }}</td>
                    <td>{{ $rentaPendiente->estatus }}</td>
                    <td>{{ $rentaPendiente->observaciones }}</td>
                    <td>{{ $rentaPendiente->gerente }}</td>


                    {!! Form::open(['route' => ['rentaPendientes.destroy', $rentaPendiente->id_rentas], 'method' => 'delete']) !!}
                    {{-- <a href="{{ route('rentaPendientes.show', [$rentaPendiente->id_rentas]) }}"
                                class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a> --}}
                    <td>
                        {{-- <a href="{{ route('rentaPendientes.edit', [$rentaPendiente->id_rentas]) }}"
                                class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a> --}}
                        <a href="{{ route('rentaPendientes.edit', [$rentaPendiente->id_rentas]) }}"
                            class='btn btn-default btn-xs btn-block'>Editar</a>
                    </td>
                    <td>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </td>

                        {!! Form::close() !!}

                </tr>
            @endforeach
        </tbody>
    </table>
</div>